[yangshengji]
title = "妖神记"
url = "https://www.baozimh.com/comic/yaoshenji-taxuedongman"
entrySelector = ".supporting-text.mt-2"
titleSelector = "a"
linkSelector = "a"
[wodeweixinliansanjie]
title = "我的微信连三界"
url = "https://cn.baozimh.com/comic/wodeweixinliansanjie-iciyuandongman"
entrySelector = ".supporting-text.mt-2"
titleSelector = "a"
linkSelector = "a"
