[default]
timeout = 300
[yaoshenji]
title = "妖神记"
url = "https://www.baozimh.com/comic/yaoshenji-taxuedongman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[wodeweixinliansanjie]
title = "我的微信连三界"
url = "https://cn.baozimh.com/comic/wodeweixinliansanjie-iciyuandongman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[wangyouzhijinzhanfashi]
title = "网游之近战法师"
url = "https://cn.baozimh.com/comic/wangyouzhijinzhanfashi-samanhua"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[wangpaiyushi]
title = "王牌御史"
url = "https://cn.baozimh.com/comic/wangpaiyushi-tongyao"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[zhonghuashenyi]
title = "中华神医"
url = "https://cn.baozimh.com/comic/zhonghuashenyi-jiguangdongman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[zhongguoliangqixiansheng]
title = "中国惊奇先生"
url = "https://cn.baozimh.com/comic/zhongguoliangqixiansheng-quanyingsheng"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[woshidashenxian]
title = "我是大神仙"
url = "https://cn.baozimh.com/comic/woshidashenxian-shengshiqiaman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[zuiqiangfantaoluxitong]
title = "最强反套路系统"
url = "https://cn.baozimh.com/comic/zuiqiangfantaoluxitong-chuyingshe"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[yuanlong]
title = "元龙"
url = "https://cn.baozimh.com/comic/yuanlong-dianguangsheyuanzhurenyuanwenyuanwenhua"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[wuzhizhuansheng]
title = "无职转生"
url = "https://cn.baozimh.com/comic/wuzhizhuansheng-huzikawayuka"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[bailianchengshen]
title = "百炼成神"
url = "https://cn.baozimh.com/comic/bailianchengshen-fengxingzhe"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[congqianyouzuolingjianshan]
title = "从前有座灵剑山"
url = "https://cn.baozimh.com/comic/congqianyouzuolingjianshan-xianmanwenhua"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[wulimofashimaxiu]
title = "物理魔法使马修"
url = "https://cn.baozimh.com/comic/wulimofashimaxiu-jiabenyi"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[zhuanshengshilaimu]
title = "关于我转生变成史莱姆这档事"
url = "https://cn.baozimh.com/comic/guanyuwozhuanshengbianchengshilaimuzhedangshi-fulaichuanshangtaishujiangtanshe"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[jiemoren]
title = "戒魔人"
url = "https://cn.baozimh.com/comic/jiemoren-zhangsanfeng"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[borenchuanboruto]
title = "博人传BORUTO"
url = "https://cn.baozimh.com/comic/borenchuanboruto-anbenqishichibenganxiong"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[meiziyukexue]
title = "妹子与科学"
url = "https://cn.baozimh.com/comic/meiziyukexue-zhazhushidede"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[shisedalu]
title = "食色大陆"
url = "https://cn.baozimh.com/comic/shisedalu-daoruisi"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[zhongshengzhidushixiuxian]
title = "重生之都市修仙"
url = "https://cn.baozimh.com/comic/zhongshengzhidushixiuxian-daxingdaodongman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"
[xingwushenjue]
title = "星武神决"
url = "https://cn.baozimh.com/comic/xingwushenjue-taxuedongman"
entrySelector = ".comics-detail > .l-content:nth-child(3) > .l-box > div:nth-child(2) >.comics-chapters"
titleSelector = "a"
linkSelector = "a"