name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:30 and 17:30 UTC-0:
    - cron:  '30 1,13 * * *'
  workflow_dispatch:

env:
  CI: true
jobs:
  publish-feeds:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: microsoft/playwright-github-action@v1
    # GitHub Actions unfortunately does not support retries;
    # this is a cumbersome method of retrying twice in case of errors:
    - run: npx playwright install
    - run: npx feed-me-up-scotty || npx feed-me-up-scotty || npx feed-me-up-scotty
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
